version: '3.9'
services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    # command: 'git checkout master && npm run:dev'
    command: 'npm run server:dev'
    ports:
      - '8000:8001'
  test2:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    command: 'npm run server:dev'
    ports:
      - '8001:8001'

