---
name: Build and Push Python Image to Google Cloud Platform
on:
  push:
    branches: [main]
  pull_request:
    branch: [main]
jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: test
      PROJECT_ID: ${{ secrets.GOOGLE_PROJECT }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CRED }}
          project_id: ${{ secrets.GOOGLE_PROJECT }}
          export_default_credentials: true

      - name: Build Docker Image
        run: docker-compose up --build -d

      # - name: Automatic Tagging of Releases
      #   id: increment-git-tag
      #   run: |
      #     bash ./scripts/git_update.sh -v major

      - name: Configure Docker Client
        run: |-
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-central1-docker.pkg.dev

      # - name: Push Docker Image to Container Registry (GCR)
      #   env:
      #     GIT_TAG: ${{ steps.increment-git-tag.outputs.git-tag }}
      #   run: |-
      #     docker tag $IMAGE_NAME:latest gcr.io/$GOOGLE_PROJECT/$IMAGE_NAME:latest
      #     docker tag $IMAGE_NAME:latest gcr.io/$GOOGLE_PROJECT/$IMAGE_NAME:$GIT_TAG
      #     docker push gcr.io/$GOOGLE_PROJECT/$IMAGE_NAME:latest
      #     docker push gcr.io/$GOOGLE_PROJECT/$IMAGE_NAME:$GIT_TAG

      - name: Push Docker Image to Artifact Registry
        env:
          GIT_TAG: V0.1
        run: |-
          docker tag test:latest us-central1-docker.pkg.dev/figmaapi/demo/figmaapi:latest
          docker tag test:latest us-central1-docker.pkg.dev/figmaapi/demo/figmaapi:$GIT_TAG
          docker push us-central1-docker.pkg.dev/figmaapi/demo/figmaapi:latest
          docker push us-central1-docker.pkg.dev/figmaapi/demo/figmaapi:$GIT_TAG

      - name: Restart container
        run: |-
          gcloud compute instances update-container instance-1 --zone us-central1-a --container-image=us-central1-docker.pkg.dev/figmaapi/demo/figmaapi:latest
